# Generated by Django 5.2.3 on 2025-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='date_prepared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
