# Generated by Django 5.2.3 on 2025-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_alter_jobcard_date_prepared_alter_jobcard_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='hot_work_required',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='indice_kpi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='total_duration_hs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='total_man_hours',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
