# Generated by Django 5.2.3 on 2025-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_alter_jobcard_approved_br_alter_jobcard_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
