# Generated by Django 5.2.3 on 2025-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_materialbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('rev', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('working_code', models.CharField(max_length=50)),
                ('direct_labor', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=50)),
                ('working_code', models.CharField(max_length=50)),
                ('pmto_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('working_code', models.CharField(max_length=50)),
                ('direct_labor', models.CharField(max_length=100)),
                ('qty_direct_labor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_tooling', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
