# Generated by Django 5.2.3 on 2025-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0008_allocatedengineering_allocatedmanpower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbase',
            name='pmto_code',
        ),
        migrations.AddField(
            model_name='materialbase',
            name='basic_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Basic Material'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='job_card_number',
            field=models.CharField(default='', max_length=50, verbose_name='Job Card Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialbase',
            name='jobcard_required_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='JobCard Required Qty'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='material_segmentation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material Segmentation'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='mto_item_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='MTO Item No'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='nps1',
            field=models.CharField(blank=True, max_length=20, verbose_name='NPS 1'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='po',
            field=models.CharField(blank=True, max_length=50, verbose_name='PO'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='sequenc_no_procurement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sequenc. Nº Procurement'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='status_procurement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status Procurement'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='tag_jobcard_base',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tag JobCard Base'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='unit_req_qty',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unit Req. Qty'),
        ),
        migrations.AddField(
            model_name='materialbase',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Weight (Kg)'),
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='discipline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='working_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Working Code'),
        ),
    ]
