# Generated by Django 5.2.3 on 2025-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_remove_materialbase_pmto_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBaseNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('job_card_number', models.CharField(max_length=50, verbose_name='Job Card Number')),
                ('working_code', models.CharField(blank=True, max_length=50, verbose_name='Working Code')),
                ('discipline', models.CharField(blank=True, max_length=50)),
                ('tag_jobcard_base', models.CharField(blank=True, max_length=100, verbose_name='Tag JobCard Base')),
                ('jobcard_required_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='JobCard Required Qty')),
                ('unit_req_qty', models.CharField(blank=True, max_length=20, verbose_name='Unit Req. Qty')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Weight (Kg)')),
                ('material_segmentation', models.CharField(blank=True, max_length=100, verbose_name='Material Segmentation')),
                ('comments', models.TextField(blank=True)),
                ('sequenc_no_procurement', models.CharField(blank=True, max_length=50, verbose_name='Sequenc. Nº Procurement')),
                ('status_procurement', models.CharField(blank=True, max_length=50, verbose_name='Status Procurement')),
                ('mto_item_no', models.CharField(blank=True, max_length=50, verbose_name='MTO Item No')),
                ('basic_material', models.CharField(blank=True, max_length=100, verbose_name='Basic Material')),
                ('description', models.TextField()),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='Project Code')),
                ('nps1', models.CharField(blank=True, max_length=20, verbose_name='NPS 1')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('po', models.CharField(blank=True, max_length=50, verbose_name='PO')),
            ],
            options={
                'verbose_name': 'Material Base',
                'verbose_name_plural': 'Materials Base',
            },
        ),
    ]
