# Generated by Django 5.2.3 on 2025-06-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0010_materialbasenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialBaseNew',
        ),
    ]
