# Generated by Django 5.2.3 on 2025-06-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0013_delete_materialbase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialBaseNew',
            new_name='MaterialBase',
        ),
    ]
