# Generated by Django 5.2.3 on 2025-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0017_rename_items_jobcardnew_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCardNew',
        ),
    ]
