# Generated by Django 5.2.3 on 2025-06-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0019_jobcardnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCard',
        ),
    ]
