# Generated by Django 5.2.3 on 2025-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0021_rename_jobcardnew_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedmanpower',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
