# Generated by Django 5.2.3 on 2025-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0022_allocatedmanpower_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedmanpower',
            name='task_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
