# Generated by Django 5.2.3 on 2025-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0023_allocatedmanpower_task_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=50)),
                ('task_order', models.IntegerField()),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('percent', models.FloatField(default=0.0)),
            ],
        ),
    ]
