# Generated by Django 5.2.3 on 2025-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0024_allocatedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedtask',
            name='max_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allocatedtask',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
