# Generated by Django 5.2.3 on 2025-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0025_allocatedtask_max_hours_allocatedtask_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedtask',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
