# Generated by Django 5.2.3 on 2025-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0026_allocatedtask_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
