# Generated by Django 5.2.3 on 2025-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0027_jobcard_last_modified_at_jobcard_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedmanpower',
            name='nps1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
