# Generated by Django 5.2.3 on 2025-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0028_allocatedmanpower_nps1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedmanpower',
            name='nps1',
        ),
        migrations.AddField(
            model_name='allocatedmaterial',
            name='nps1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
