# Generated by Django 5.2.3 on 2025-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0029_remove_allocatedmanpower_nps1_allocatedmaterial_nps1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(max_length=20)),
                ('subsystem_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
