# Generated by Django 5.2.3 on 2025-07-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0031_uploadedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedModel',
        ),
    ]
