# Generated by Django 5.2.3 on 2025-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0032_delete_uploadedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbase',
            name='item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
