# Generated by Django 5.2.3 on 2025-07-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0033_alter_materialbase_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineeringbase',
            old_name='tag',
            new_name='jobcard_number',
        ),
    ]
